name: Test
on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'temp'
      - 'debug'
  push:
    branches:
      - main
      - develop
      - 'releases/**'
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'temp'
      - 'debug'

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci --ignore-scripts
        env:
          CI: true
          COVERAGE: true

      - name: Format
        run: npm run format-check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci
